---
- name: configure_zabbix_agent | installing agent package
  apt:
    name: "zabbix-agent"
    state: latest
  when: ansible_os_family == "Debian"

- name: configure_zabbix_agent | configuring agent
  template:
    src: "etc/zabbix/zabbix_agentd.conf.j2"
    dest: "/etc/zabbix/zabbix_agentd.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart zabbix-agent
